apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: swagger-petstore4
  description: Swagger Petstore v4 sample API
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://petstore3.swagger.io/api/v3/openapi.json
